name: Running File 1  push example/packer directory

on:
  push:
    branches: [ "main" ]
    paths:
      - 'example/packer/**'
      
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo hello world file 1 after changing in example/packer directory
