name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Packer Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check if Main workflow has executed
        id: check_main
        run: |
          if [ -f main_executed.txt ]; then
            echo "executed=true" >> $GITHUB_ENV
          fi
      - name: Run a one-line script
        if: env.executed != 'true'
        run: echo "Hello, world! from Main workflow."
