name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Packer Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check if Main workflow has executed
        run: |
          if [ -f main_executed.txt ]; then
            echo "Main workflow already executed"
            exit 78
          else
            echo "Main workflow not executed yet"
          fi
      - name: Run main workflow
        run: echo "Hello, world! from Main workflow."
