name: Running Main Workflow 
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Executing main-workflow jobs
        run: echo Hello, world! from Main workflow. 
      
