name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Packer Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello, world! from Main workflow."
