name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Packer Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_run'
    steps:
      - uses: actions/checkout@v4
      - name: Running Main-workflow
        run: echo "Hello, world! from Main workflow."
