name: Workflow Two

on:
  workflow_run:
    workflows: [ packer-workflow.yml ]  # Trigger on completion of workflow1.yml
    types: [ completed ]           # Only run on successful completion

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Your deployment steps here
      - name: Deploy the project
        run: make deploy

