name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["packer-workflow.yaml"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello from Main-workflow 
        run: echo "Hello, world! from Main workflow."
