name: Packer Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'example/packer/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Job from packer-workflow
        run: echo "Change detected in example/packer directory"
