name: Workflow One

on:
  # Your push or pull request trigger event here
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Your build steps here
      - name: Build the project
        run: make build

      - name: Output a success message (optional)
        run: echo "Workflow packer completed successfully!"
        # This is for informational purposes only

