name: Running Packer-Workflow file

on:
  push:
    branches: [ "main" ]
    paths:
      - 'example/packer/**'
      
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello from Packer-workflow
        run: echo "Changes detected in example/packer directory so the packer-workflow executes"
