name: Packer Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'example/packer/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Change detected in example/packer directory"
      - name: Create execution flag
        run: echo "executed" >> main_executed.txt
        working-directory: ${{ github.workspace }}
