name: Running Packer-Workflow file
on:
  push:
    branches: [ "main" ]
    paths:
      - 'example/packer/**'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create and store artifact
        run: |
          echo "This is a sample text file." > sample.txt
          # Save the sample.txt as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sample-text-file
          path: sample.txt
